[random]
seed = 0

[path]
# dataset = "../data/DNS2021/dns_interspeech_2021_mandarin_100h"
dataset = "../data/DNS2021/dns_interspeech_2021_mandarin_1h"

[dataset]
audio_format = "wav"
valid_ratio = 0.1
test_ratio = 0.1
