[path]
# local pc
# zip = "D:/ML/datasets/dns_interspeech_2021_mandarin_100h.zip"
# aistudio

# The relative path is based on the current working directory , not the unzip.py
# zip = "../data/DNS2021/dns_interspeech_2021_mandarin_100h.zip"
zip = "../data/DNS2021/dns_interspeech_2021_mandarin_1h.zip"
